definitions:
  entity.Chatitem:
    properties:
      fromaddr:
        type: string
      id:
        type: integer
      message:
        type: string
      nftaddr:
        type: string
      nftid:
        type: string
      read:
        type: boolean
      sender_name:
        type: string
      timestamp:
        type: string
      timestamp_dtm:
        type: string
      toaddr:
        type: string
    type: object
  entity.Chatiteminbox:
    properties:
      chain:
        type: string
      context_type:
        type: string
      fromaddr:
        type: string
      id:
        type: integer
      logo:
        type: string
      message:
        type: string
      name:
        type: string
      nftaddr:
        type: string
      nftid:
        type: string
      read:
        type: boolean
      sender_name:
        type: string
      timestamp:
        type: string
      timestamp_dtm:
        type: string
      toaddr:
        type: string
      type:
        type: string
      unread:
        type: integer
    type: object
host: restwalletchat-app-sey3k.ondigitalocean.app
info:
  contact:
    email: walletchatextension@gmail.com
    url: https://walletchat.fun
  description: This is the WalletChat messagez
  title: WalletChat API
  version: "1.0"
paths:
  /create_chatitem:
    post:
      consumes:
      - application/json
      description: For DMs, CreateChatItem is used to store the message in the backed
        database
      parameters:
      - description: Direct Message Chat Data
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/entity.Chatitem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatitem'
            type: array
      summary: Create/Insert DM chat message (1-to-1 messaging)
      tags:
      - DM
  /get_inbox/{address}:
    get:
      consumes:
      - application/json
      description: Get Each 1-on-1 Conversation, NFT and Community Chat For Display
        in Inbox
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatiteminbox'
            type: array
      summary: Get Inbox Summary With Last Message
      tags:
      - inbox
  /get_unread_cnt/{address}:
    get:
      consumes:
      - application/json
      description: Get Each 1-on-1 Conversation, NFT and Community Chat For Display
        in Inbox
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Get all unread messages TO a specific user, used for total count notification
        at top notification bar
      tags:
      - inbox
  /get_unread_cnt/{address}/{nftaddr}/{nftid}:
    get:
      consumes:
      - application/json
      description: Get Unread count for specifc NFT context given a wallet address
        and specific NFT
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      - description: NFT Contract Address
        in: path
        name: nftaddr
        required: true
        type: string
      - description: NFT ID
        in: path
        name: nftid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Get all unread messages for a specific NFT context
      tags:
      - inbox
  /get_unread_cnt/{fromaddr}/{toaddr}:
    get:
      consumes:
      - application/json
      description: Get Unread count for DMs (>_<)
      parameters:
      - description: 'TO: Wallet Address'
        in: path
        name: toaddr
        required: true
        type: string
      - description: 'FROM: Wallet Address'
        in: path
        name: from
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Get all unread messages between two addresses
      tags:
      - inbox
  /get_unread_cnt_by_type/{address}/{type}:
    get:
      consumes:
      - application/json
      description: Get Each 1-on-1 Conversation, NFT and Community Chat For Display
        in Inbox (>_<)
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      - description: Message Type - nft|community|dm|all
        in: path
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Get all unread messages TO a specific user, used for total count notification
        at top notification bar
      tags:
      - inbox
  /get_unread_cnt_nft/{address}:
    get:
      consumes:
      - application/json
      description: Get Unread count for all NFT contexts given a wallet address (>_<)
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Get all unread messages for all NFT related chats for given user
      tags:
      - inbox
  /getall_chatitems:
    get:
      consumes:
      - application/json
      description: Get Entire Chatitems table
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatitem'
            type: array
      summary: Get All Chat Items (legacy - not used currently)
      tags:
      - inbox
  /getall_chatitems/{address}:
    get:
      consumes:
      - application/json
      description: Get all Chat Items for DMs for a given wallet address (>_<)
      parameters:
      - description: Wallet Address
        in: path
        name: toaddr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatitem'
            type: array
      summary: Get Chat Item For Given Wallet Address
      tags:
      - inbox
  /getall_chatitems/{fromaddr}/{toaddr}:
    get:
      consumes:
      - application/json
      description: Get chat data between the given two addresses, TO and FROM and
        interchangable here
      parameters:
      - description: 'TO: Wallet Address'
        in: path
        name: toaddr
        required: true
        type: string
      - description: 'FROM: Wallet Address'
        in: path
        name: from
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatitem'
            type: array
      summary: Get Chat Data Between Two Addresses
      tags:
      - inbox
  /getnft_chatitems/{address}:
    get:
      consumes:
      - application/json
      description: Get ALL NFT context items for a given wallet address (>_<)
      parameters:
      - description: Wallet Address
        in: path
        name: toaddr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatitem'
            type: array
      summary: Get NFT Related Chat Items For Given Wallet Address
      tags:
      - inbox
  /getnft_chatitems/{address}/{nftaddr}/{nftid}:
    get:
      consumes:
      - application/json
      description: Get all specified NFT contract and ID items for a given wallet
        address (>_<)
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      - description: NFT Contract Address
        in: path
        name: nftaddr
        required: true
        type: string
      - description: NFT ID
        in: path
        name: nftid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatitem'
            type: array
      summary: Get NFT Related Chat Items For Given NFT Contract and ID, relating
        to one wallet
      tags:
      - inbox
  /getnft_chatitems/{fromaddr}/{toaddr}/{nftaddr}/{nftid}:
    get:
      consumes:
      - application/json
      description: Get ALL NFT context items for a specifc NFT context convo between
        two wallets
      parameters:
      - description: NFT Contract Address
        in: path
        name: nftaddr
        required: true
        type: string
      - description: NFT ID
        in: path
        name: nftid
        required: true
        type: string
      - description: 'TO: Wallet Address'
        in: path
        name: toaddr
        required: true
        type: string
      - description: 'FROM: Wallet Address'
        in: path
        name: from
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatitem'
            type: array
      summary: Get NFT Related Chat Items For Given NFT Contract and ID, between two
        wallet addresses (TO and FROM are interchangable)
      tags:
      - inbox
  /getnft_chatitems/{nftaddr}/{nftid}:
    get:
      consumes:
      - application/json
      description: Get ALL NFT context items for a given wallet address (>_<)
      parameters:
      - description: NFT Contract Address
        in: path
        name: nftaddr
        required: true
        type: string
      - description: NFT ID
        in: path
        name: nftid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Chatitem'
            type: array
      summary: Get NFT Related Chat Items For Given NFT Contract and ID
      tags:
      - inbox
  /unreadcount/{address}:
    get:
      consumes:
      - application/json
      description: Get Unread count just given an address
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Get all unread messages TO a specific user, used for total count notification
        at top notification bar
      tags:
      - inbox
swagger: "2.0"
